# Generated by Django 5.2 on 2026-04-24 00:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='type',
            field=models.CharField(choices=[('new_product', 'منتج جديد من تاجر تتابعه'), ('order_status_update', 'تحديث حالة الطلب'), ('new_order', 'طلب جديد مستلم'), ('order_cancelled', 'تم إلغاء الطلب'), ('new_message', 'رسالة جديدة'), ('follow', 'متابع جديد'), ('payment_submitted', 'وصل دفع جديد مُرفق'), ('payment_approved', 'تم قبول وصل الدفع'), ('payment_rejected', 'تم رفض وصل الدفع'), ('new_review', 'تقييم جديد'), ('review_reply', 'رد على تقييمك'), ('appeal_submitted', 'طعن جديد للمراجعة'), ('appeal_decision', 'قرار بشأن طعنك'), ('general', 'إشعار عام')], default='general', max_length=50),
        ),
    ]
