# Generated by Django 5.2 on 2026-04-20 20:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_order_receipt_image_order_transaction_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='receipt_image',
        ),
        migrations.RemoveField(
            model_name='order',
            name='transaction_id',
        ),
        migrations.AlterField(
            model_name='order',
            name='payment_method',
            field=models.CharField(choices=[('cod', 'الدفع عند الاستلام'), ('card', 'بطاقة بنكية'), ('ccp', 'بريد الجزائر'), ('baridimob', 'بريدي موب (BaridiMob)')], default='cod', max_length=20),
        ),
        migrations.AlterField(
            model_name='order',
            name='payment_status',
            field=models.CharField(choices=[('pending', 'في انتظار الدفع'), ('proof_uploaded', 'تم رفع الوصل'), ('paid', 'مدفوع'), ('rejected', 'مرفوض'), ('failed', 'فشل'), ('refunded', 'مسترجع')], default='pending', max_length=20),
        ),
        migrations.CreateModel(
            name='PaymentProof',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='orders/receipts/')),
                ('transaction_id', models.CharField(blank=True, default='', max_length=100)),
                ('amount', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('status', models.CharField(choices=[('pending', 'قيد الانتظار'), ('approved', 'مقبول'), ('rejected', 'مرفوض')], default='pending', max_length=20)),
                ('rejection_reason', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='proofs', to='orders.order')),
            ],
            options={
                'verbose_name': 'إثبات دفع',
                'verbose_name_plural': 'إثباتات الدفع',
                'ordering': ['-created_at'],
            },
        ),
    ]
