# Generated by Django 5.2 on 2026-04-19 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productvariant',
            name='image',
            field=models.TextField(blank=True, default=''),
        ),
    ]
