# Generated by Django 5.2 on 2026-04-20 13:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_report'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='appeal_deadline',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('suspended', 'Suspended'), ('pending_delete', 'Pending Delete'), ('deleted', 'Deleted')], default='active', max_length=20),
        ),
        migrations.AddField(
            model_name='user',
            name='suspended_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='suspension_reason',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='AdminActionLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('suspend', 'Suspend'), ('restore', 'Restore'), ('delete', 'Delete'), ('permanent_delete', 'Permanent Delete')], max_length=20)),
                ('target_model', models.CharField(max_length=50)),
                ('target_id', models.IntegerField()),
                ('target_name', models.CharField(blank=True, default='', max_length=255)),
                ('reason', models.TextField(blank=True, default='')),
                ('before_state', models.JSONField(blank=True, null=True)),
                ('after_state', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('admin_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='admin_actions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'سجل عمليات المسؤول',
                'verbose_name_plural': 'سجلات عمليات المسؤولين',
                'ordering': ['-created_at'],
            },
        ),
    ]
