# Generated by Django 5.2 on 2026-04-20 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_user_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='adminactionlog',
            name='is_processed',
            field=models.BooleanField(default=False),
        ),
    ]
