# Generated by Django 5.2 on 2026-04-20 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_adminactionlog_is_processed'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='buyer_rating',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=3),
        ),
        migrations.AddField(
            model_name='profile',
            name='buyer_reviews_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='profile',
            name='seller_rating',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=3),
        ),
        migrations.AddField(
            model_name='profile',
            name='seller_reviews_count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
