# Generated by Django 5.2 on 2026-04-20 22:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_appeal'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='baridimob_id',
            field=models.CharField(blank=True, default='', max_length=50, verbose_name='رقم RIP أو BaridiMob'),
        ),
        migrations.AddField(
            model_name='profile',
            name='ccp_name',
            field=models.CharField(blank=True, default='', max_length=200, verbose_name='الاسم الكامل في الحساب'),
        ),
        migrations.AddField(
            model_name='profile',
            name='ccp_number',
            field=models.CharField(blank=True, default='', max_length=20, verbose_name='رقم الحساب البريدي (CCP)'),
        ),
    ]
