# Generated by Django 5.2 on 2026-04-25 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_store'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='store_category',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='store_description',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='store_logo',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='store_name',
        ),
        migrations.AlterField(
            model_name='store',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
