# Generated by Django 5.2 on 2026-04-22 12:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_suborder_orderitem_sub_order_paymentproof_sub_order'),
        ('reviews', '0004_sellerreview_shipping_rating_reviewimage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='buyerreview',
            name='order',
        ),
        migrations.RemoveField(
            model_name='sellerreview',
            name='order',
        ),
        migrations.AddField(
            model_name='buyerreview',
            name='sub_order',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='buyer_reviews', to='orders.suborder'),
        ),
        migrations.AddField(
            model_name='sellerreview',
            name='sub_order',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='seller_reviews', to='orders.suborder'),
        ),
    ]
